# -*- coding: utf-8 -*-
"""YOLOV8_Detección.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r73e2UJD2-3J6ycZC8evk0GWuNCl_Flm
"""

!pip install roboflow

!pip install ultralytics

from roboflow import Roboflow
from ultralytics import YOLO

import os
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
from pathlib import Path

"""Configuración de acceso a Roboflow

"""

rf = Roboflow(api_key="8m6bzS5ZOJmJIPj9JDS1")
project = rf.workspace("coellocoronel").project("vehiculos-hkrqk")
version = project.version(6)
dataset = version.download("yolov8")

# Instanciar el modelo YOLOv8
model = YOLO("yolov8n.pt")

# Usar el archivo de configuración en lugar de una ruta de carpeta
results = model.train(
    data="/content/Vehiculos-6/data.yaml",  # Ruta al archivo .yaml que acabas de crear
    epochs=20,
    batch=16,
    imgsz=640,
    patience=20,
    verbose=True
)

# Guardar el modelo entrenado
model.save(f"modelo_entrenado.pt")

from ultralytics import YOLO
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import yaml
import os

def evaluate_yolo_model(model_path, data_yaml, conf_thresholds=[0.25, 0.45, 0.65]):
    results = {}
    model = YOLO(model_path)

    for conf in conf_thresholds:
        metrics = model.val(data=data_yaml,
                          conf=conf,
                          iou=0.5)

        results[conf] = {
            'precision': float(metrics.box.mp),
            'recall': float(metrics.box.mr),
            'mAP50': float(metrics.box.map50),
            'mAP': float(metrics.box.map)
        }

    return results

def get_validation_data(data_yaml):
    """
    Obtiene la ruta del conjunto de validación desde el archivo data.yaml
    """
    with open(data_yaml, 'r') as f:
        data = yaml.safe_load(f)

    # Obtener el directorio base donde está el archivo data.yaml
    base_dir = os.path.dirname(os.path.abspath(data_yaml))

    # Convertir rutas relativas a absolutas
    val_path = os.path.join(base_dir, data['val'])
    if 'names' in data:
        class_names = data['names']
    else:
        class_names = [f"clase_{i}" for i in range(data['nc'])]

    return val_path, class_names

def plot_confusion_matrix(conf_matrix, class_names):
    """
    Visualiza la matriz de confusión
    """
    # Obtener los valores de la matriz como array
    matrix = conf_matrix.matrix

    # Convertir a numpy array si no lo es
    if not isinstance(matrix, np.ndarray):
        matrix = np.array(matrix)

    # Normalizar por filas
    with np.errstate(divide='ignore', invalid='ignore'):
        matrix_normalized = matrix / matrix.sum(axis=1, keepdims=True)
        matrix_normalized = np.nan_to_num(matrix_normalized)

    # Visualizar
    plt.figure(figsize=(10, 8))
    sns.heatmap(matrix_normalized,
                annot=True,
                fmt='.2f',
                cmap='Blues',
                xticklabels=class_names,
                yticklabels=class_names)
    plt.title('Matriz de Confusión Normalizada')
    plt.xlabel('Predicción')
    plt.ylabel('Valor Real')
    plt.tight_layout()
    plt.show()

    return matrix_normalized

def plot_metrics(results_df):
    plt.figure(figsize=(12, 6))
    for metric in results_df.columns:
        plt.plot(results_df.index, results_df[metric], marker='o', label=metric)
    plt.title('Métricas vs Umbral de Confianza')
    plt.xlabel('Umbral de Confianza')
    plt.ylabel('Valor')
    plt.legend()
    plt.grid(True)
    plt.show()

def plot_class_metrics(metrics, class_names):
    precisions = metrics.box.p
    recalls = metrics.box.r
    ap50s = metrics.box.ap50

    df = pd.DataFrame({
        'Precision': precisions,
        'Recall': recalls,
        'AP50': ap50s
    }, index=class_names)

    plt.figure(figsize=(12, 6))
    df.plot(kind='bar')
    plt.title('Métricas por Clase')
    plt.xlabel('Clase')
    plt.ylabel('Valor')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    return df

def analyze_model_performance(model_path, data_yaml):
    """
    Realiza un análisis completo del rendimiento del modelo
    """
    model = YOLO(model_path)

    # Obtener nombres de clases
    _, class_names = get_validation_data(data_yaml)

    # Evaluar con diferentes umbrales de confianza
    conf_thresholds = [0.25, 0.45, 0.65]
    results = evaluate_yolo_model(model_path, data_yaml, conf_thresholds)

    # Crear DataFrame con resultados
    df_results = pd.DataFrame(results).T
    print("\nResultados por umbral de confianza:")
    print(df_results)

    # Visualizar resultados generales
    plot_metrics(df_results)

    # Validación con configuración óptima y obtención de matriz de confusión
    metrics = model.val(data=data_yaml,
                       conf=0.45,
                       iou=0.5)

    # Imprimir resultados detallados
    print("\nResultados detallados con conf=0.45:")
    print(f"mAP50: {float(metrics.box.map50):.4f}")
    print(f"mAP: {float(metrics.box.map):.4f}")
    print(f"Precisión Media: {float(metrics.box.mp):.4f}")
    print(f"Recall Medio: {float(metrics.box.mr):.4f}")

    # Obtener y visualizar la matriz de confusión
    print("\nGenerando matriz de confusión...")
    confusion_matrix = metrics.confusion_matrix
    conf_matrix_norm = plot_confusion_matrix(confusion_matrix, class_names)

    # Analizar métricas por clase
    print("\nMétricas por clase:")
    class_metrics = plot_class_metrics(metrics, class_names)
    print(class_metrics)

    return metrics, df_results, conf_matrix_norm

# Ejemplo de uso
model_path = '/content/modelo_entrenado.pt'
data_yaml = '/content/Vehiculos-6/data.yaml'

metrics, results_df, conf_matrix = analyze_model_performance(model_path, data_yaml)